### ISSUE TITLE
Staff Page Overhaul

### ISSUE THREAD

**Issue by katalinadeaven** [engagingnewsproject/enp-platform#115]
Staff page edits

- [x] Add Center Leadership page (needs hierarchy ability)
- [x] Verticals have PIs at the top, then go alphabetically
- [x] Staff page becomes Administrative and Technology (alphabetical)
- [x] Delete technology page
- [x] Add Collaborators page (show name, title, organization)

**Comment by leoncai1999** [comment]
Updates:

1. I have added in the Center Leadership page, but am still working on having Center Leadership appear at the top of the menu.

2. We still don't know who should be on the Collaborators page or what it should look like yet, so we are holding off on that for now.

**Comment by leoncai1999** [comment]
Update: The overhaul is almost complete. There's only one issue left. When the user clicks on staff, we want the first group in the menu to be selected by default ('Center Leadership'). However, the second item is selected by default as shown below
![Screen Shot 2021-03-12 at 2 21 39 PM](https://user-images.githubusercontent.com/31896484/110994369-5019a100-833e-11eb-8062-36890d5e2b8e.png)

**Comment by leoncai1999** [comment]
This issue is now resolved and the overhaul is complete. A PR has been opened here: https://github.com/engagingnewsproject/enp-platform/pull/141

**Comment by NWebb5** [comment]
Issue is now closed.

**Comment by luukee** [comment]
@leoncai1999 @NWebb5 The sidebar URL's are switching between `vertical` to `category`. They should all be `vertical`. I believe this was something you guys worked on. 

See Kat's comment:

_"Can you take a look at this page and see why Sam (Samuel C. Woolley) isn't showing up at the top since he's program director? He used to, not sure what changed. https://mediaengagement.org/team/category/propaganda/"_

link you sent is: /team/category/propaganda/,
whereas on my local development site & the dev site the link is: /vertical/propaganda/team/
if visiting from Propaganda/Research/sidebar.
same for the dev site & my local: /vertical/propaganda/team/
if visiting from Footer/Staff/Propaganda
So how in the world did you find the “category” link? 🙀
The Team sidebar has differing links for each “category/vertical”.

Propaganda, Administrative and Technology and Collaborators use the “category”, the rest of the links use the “vertical”. Interesting bug indeed!

https://mediaengagement.org/team/vertical/center-leadership
https://mediaengagement.org/team/vertical/journalism
https://mediaengagement.org/team/vertical/media-ethics
https://mediaengagement.org/team/category/propaganda
https://mediaengagement.org/team/vertical/science-communication
https://mediaengagement.org/team/category/administrative-and-technology
https://mediaengagement.org/team/category/collaborators
Issue lies in either of these files:

themes/engage/src/Models/FilterMenu.php
themes/engage/src/Models/VerticalsFilterMenu.php

**Comment by luukee** [comment]
@katalinadeaven Hey Kat, I believe we have what you are looking for. You can compare these two pages:

- https://cmedev.wpengine.com/team/category/propaganda/
- https://cmedev.wpengine.com/team/vertical/propaganda/

. . . and if you could look through the other sidebar links & let me know if it's good for you.
Thanks!

**Comment by katalinadeaven** [comment]
@luukee The only issues I see are with the Center Leadership pages. Everyone should be listed in reverse order (starting with Talia, Gina, Melody, Anthony, Scott, Sam, then me)

**Comment by luukee** [comment]
@katalinadeaven You got it! https://cmedev.wpengine.com/team/vertical/center-leadership/

Let me know if everything looks ok. Thanks Kat!

**Comment by katalinadeaven** [comment]
@luukee Looks good!

**Comment by luukee** [comment]
Great @katalinadeaven! I'll push to the live site :)

Thanks Kat!

**Comment by luukee** [comment]
Pushed @katalinadeaven 

- https://mediaengagement.org/team/vertical/center-leadership/
- https://mediaengagement.org/team/category/propaganda/

Let me know if you need any changes. Thanks!
